### ISSUE TITLE
Redraw event won't trigger when using bucket only

### ISSUE THREAD

**Issue by zlyfer** [Ikos9/canvas-free-drawing#1] opened 2018-11-24 01:32 UTC
Hey,

when only using the bucket/fill method the redraw event won't be triggered.
When drawing with the normal free drawing mode and then using the bucket all works fine, when using the bucket on an empty canvas it won't.

Would be nice if that get's fixed.

Cheers.

**Comment by Ikos9** [comment] 2018-11-24 09:13
Hello, I already suspect the cause of this bug so it should be an easy fix.

I also have a bigger update to release so I'll probably ship the fix with that, hopefully this weekend!

Thank you for the report, it's pretty sweet to know that someone else use this library!

**Comment by Ikos9** [comment] 2018-11-25 10:18
I tried a couple of times to increase the performance of the fill function but it's still slower than what I'd like to.
If you'd like to pull a change or suggest anything to speed it up I'll be glad to merge or try it!

Staying in topic, this issue has been fixed on my local repository, I'll release it as soon as I finish add the new APIs to the docs.

Cheers.

**Comment by Ikos9** [comment] 2018-11-25 12:33
Fixed in v1.3.0

**Closed** 2018-11-25 12:32 UTC
